#!/bin/sh

# Create success markdown file in the project root directory
cat > /app/project/docker-success.md << EOF
# Docker Success Report

## Congratulations! 🎉

**Congrats, you successfully ran your Dockerfile.**

### Environment Details:
- **Student Name**: ${STUDENT_NAME:-Unknown}
- **Course Name**: ${COURSE_NAME:-Unknown}
- **Container Name**: advanced-programming-webapp
- **Timestamp**: $(date '+%Y-%m-%d %H:%M:%S')
- **Hostname**: $(hostname)

### What This Means:
You have successfully:
1. Built a Docker image from your Dockerfile
2. Started a container using Docker Compose
3. Mapped ports correctly (8080:80)
4. Created a file in the host filesystem from the container
5. Used environment variables in your container

### Next Steps:
1. Commit this file to your Git repository
2. Create a new branch for your next task
3. Continue with the Git exercises

---
*This file was automatically generated by your Docker container*
EOF

echo "Success file created at /app/project/docker-success.md"
echo "This file is now available in your project root directory"
echo "Contents:"
cat /app/project/docker-success.md

# Start nginx in the background
nginx -g "daemon off;" &

# Keep the container running
wait